# Generated by Django 6.0.3 on 2026-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_account_balance_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.TextField(unique=True),
        ),
    ]
